spring: 
  application: 
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/yueyang?serverTimezone=UTC
    username: root
    password: abc1176478896
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

