server:
  port: 443
  ssl:
    key-store: classpath:www.yueyangskt.com.jks
    key-password: okpm3a8y2e
    key-store-type: JKS
#    key-alias: 1

spring: 
  application: 
    name: gateway
  datasource:
    url: jdbc:mysql://localhost:3306/yueyang?serverTimezone=UTC
    username: root
    password: abc1176478896
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: 123456
    timeout: 3000
    lettuce:
      pool:
        max-active: 100   # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 20     # 连接池中的最大空闲连接
        min-idle: 8     # 连接池中的最小空闲连接
        max-wait: 10000      # 连接池最大阻塞等待时间（使用负值表示没有限制）

#zuul:
#  servlet-path: /
#  routes:
#    first:
#      path: /zuul
#      url: http://www.yueyangskt.com/

ribbon:
  OkToRetryOnAllOperations: false #对所有操作请求都进行重试,默认false
  ReadTimeout: 5000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 5000 #ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     #对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 #对切换实例的重试次数，默认1

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          enabled: true #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

